[[collection]]
type = "card"
title = "civic-ops"
link = "https://github.com/ashraddhansh/civic-ops"
content = "civic-ops is a moblie application by which users can report civic issues to the municipality."

[[collection]]
type = "card"
title = "Asteroids"
link = "https://github.com/ashraddhansh/Asteroids"
content = "It is the copy of old Asteroids I made to learn OOPs in python."

[[collection]]
type = "card"
title = "Cursor Barebone"
link = "https://github.com/ashraddhansh/Cursor-Barebone"
content = "This is a CLI small AI agent project that functions similarly (in a rudimentary way) to LLM-based code agents such as Cursor or Claude."
